- hosts: all
  roles:
    - common
    - git
    - role: homebrew
      tags:
        - osx
    - apps
    - haskell
    - emacs
    - role: osx
      tags:
        - osx
    - java
    - python
    - erlang
    - pass
  vars:
    user: "{{ ansible_env.USER }}"
    home_dir: "{{ ansible_env.HOME }}"
    homebrew_packages:
      - python3
      - ansible
      - node
      - terminal-notifier
      - ghc
      - cabal-install
      - gmp
      - sbt
      - ocaml
      - opam
      - asdf
      - heroku
      - fd
      - keybase
      - pass
      - tmux
    ubuntu_packages:
      - git
      - emacs
      - make
    ubuntu_snaps:
      - snap_name: telegram-desktop
        classic: False
      - snap_name: slack
        classic: True
    osx_apps:
      - package_name: "google-chrome"
        app_name: "Google Chrome"
      - package_name: "telegram"
        app_name: "Telegram"
      - package_name: "caffeine"
        app_name: "Caffeine"
      - package_name: "vlc"
        app_name: "VLC"
      - package_name: "virtualbox"
        app_name: "Virtualbox"
        path: "/Applications/VirtualBox.app"
      # - package_name: "twitter"
      #   app_name: "Twitter"
      # - package_name: "optimal-layout"
      #   app_name: "Optional Layout"
      - package_name: "vagrant"
        app_name: "Vagrant"
        path: "/opt/vagrant"
      - package_name: "emacs"
        app_name: "Emacs"
        path: "/Applications/Emacs.app"
      - package_name: "transmission"
        app_name: "Transmission"
      - package_name: "dropbox"
        app_name: "Dropbox"
      - package_name: "the-unarchiver"
        app_name: "The Unarchiver"
      - package_name: "visual-studio-code"
        app_name: "Visual Studio Code"
        path: "/Applications/Visual Studio Code.app"
