- hosts: all
  roles:
    - common
    - git
    - role: homebrew
      tags:
        - osx
    - apps
    - haskell
    - emacs
    - role: osx
      tags:
        - osx
    - java
    - python
    - erlang
    - pass
  vars:
    user: "{{ ansible_env.USER }}"
    home_dir: "{{ ansible_env.HOME }}"
    homebrew_packages:
      - python3
      - keybase
      - pass
      - tmux
    ubuntu_packages:
      - git
      - emacs
      - make
    ubuntu_snaps:
      - snap_name: telegram-desktop
        classic: False
      - snap_name: slack
        classic: True
    osx_apps:
      - package_name: "telegram"
        app_name: "Telegram"
      - package_name: "vlc"
        app_name: "VLC"
      - package_name: "transmission"
        app_name: "Transmission"
      - package_name: "dropbox"
        app_name: "Dropbox"
      - package_name: "the-unarchiver"
        app_name: "The Unarchiver"
      - package_name: "visual-studio-code"
        app_name: "Visual Studio Code"
        path: "/Applications/Visual Studio Code.app"
