- hosts: all
  roles:
    - common
    - git
    - role: homebrew
      tags:
        - osx
    - apps
    - emacs
    - role: osx
      tags:
        - osx
    - pass
    - role: ubuntu
      tags: ubuntu
  vars:
    user: "{{ ansible_env.USER }}"
    home_dir: "{{ ansible_env.HOME }}"
    homebrew_packages:
      - python3
      - keybase
      - pass
      - tmux
    ubuntu_repos:
      - "ppa:numix/ppa"
    ubuntu_packages:
      - git
      - emacs
      - make
      - pass
      - vlc
      - synaptic
      - gnome-shell-extensions
      - ubuntu-restricted-extras
      - preload
      - numix-gtk-theme
      - bleachbit
      - xkeycaps
    ubuntu_snaps:
      - snap_name: telegram-desktop
        classic: False
      - snap_name: slack
        classic: True
      - snap_name: spotify
        classic: False
      - snap_name: brave
        classic: False
    osx_apps:
      - package_name: "telegram"
        app_name: "Telegram"
      - package_name: "vlc"
        app_name: "VLC"
      - package_name: "transmission"
        app_name: "Transmission"
      - package_name: "dropbox"
        app_name: "Dropbox"
      - package_name: "the-unarchiver"
        app_name: "The Unarchiver"
      - package_name: "visual-studio-code"
        app_name: "Visual Studio Code"
        path: "/Applications/Visual Studio Code.app"
