- hosts: all
  roles:
    - common
    - git
    # - homebrew
    - rbenv
    # - apps
    - haskell
    - emacs
    # - osx
  vars:
    user: "{{ ansible_env.USER }}"
    home_dir: "{{ ansible_env.HOME }}"
    homebrew_packages:
      - rbenv
      - ruby-build
      - python
      - ansible
      - httpie
      - hub
      - node
      - terminal-notifier
      - ghc
      - cabal-install
      - brew-cask
      - gmp
      - jenv
      - sbt
    osx_apps:
      - package_name: "google-chrome"
        app_name: "Google Chrome"
      # - package_name: "telegram"
      #   app_name: "Telegram"
      - package_name: "caffeine"
        app_name: "Caffeine"
      - package_name: "cloud"
        app_name: "CloudApp"
      - package_name: "firefox"
        app_name: "Firefox"
      - package_name: "virtualbox"
        app_name: "Virtualbox"
        path: "/Applications/VirtualBox.app"
      # - package_name: "twitter"
      #   app_name: "Twitter"
      - package_name: "optimal-layout"
        app_name: "Optional Layout"
      - package_name: "vagrant"
        app_name: "Vagrant"
        path: "/opt/vagrant"
      - package_name: "sketch"
        app_name: "Sketch"
      - package_name: "emacs"
        app_name: "Emacs"
      - package_name: "java"
        app_name: "Latest Java"
        path: "/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk"
      - package_name: "java7"
        app_name: "Java 7"
        path: "/Library/Java/JavaVirtualMachines/jdk1.7.0_75.jdk"
