---
- name: erlang 19.3 version added as a build
  shell: "kerl build 19.3 19.3"
  args:
    creates: "{{ home_dir }}/.kerl/builds/19.3"

- name: erlang installation dir exists
  file:
    state: directory
    path: "{{ home_dir }}/kerl"

- name: erlang 19.3 version installed
  shell: "kerl install 19.3 {{ home_dir }}/kerl/19.3"
  args:
    creates: "{{ home_dir }}/kerl/19.3"
