---
- name: erlang 19.3 version added as a build
  shell: "kerl build 19.3 19.3"
  args:
    creates: "{{ kerl_builds_dir }}/builds/{{ default_erlang_version }}"

- name: erlang installation dir exists
  file:
    state: directory
    path: "{{ kerl_installations_dir }}"

- name: erlang 19.3 version installed
  shell: "kerl install {{ default_erlang_version }} {{ default_erlang_installation_dir }}"
  args:
    creates: "{{ default_erlang_installation_dir }}"
