- name: homebrew installed
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    creates: "/usr/local/bin/brew"

- name: opt directory exists
  file:
    state: directory
    path: "/opt"
  become: True

- name: cask directory writable
  file:
    state: directory
    path: "/opt/homebrew-cask"
    owner: "{{ user }}"
  become: True

- name: homebrew up to date
  homebrew:
    update_homebrew: True

- name: homebrew packages installed
  homebrew:
    name: "{{ homebrew_packages }}"
    state: present
