- name: homebrew installed
  shell: "curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install | ruby"
  args:
    creates: "/usr/local/bin/brew"

- name: sborrazas repository added
  shell: "brew tap sborrazas/casks"
  args:
    creates: "/usr/local/Homebrew/Library/Taps/sborrazas"

- name: opt directory exists
  file:
    state: directory
    path: "/opt"
  become: True

- name: cask directory writable
  file:
    state: directory
    path: "/opt/homebrew-cask"
    owner: "{{ user }}"
  become: True

- name: homebrew up to date
  homebrew:
    update_homebrew: True

- name: homebrew packages installed
  homebrew:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew_packages }}"
