- name: homebrew installed
  shell: "curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install | ruby"
  args:
    creates: "/usr/local/bin/brew"

- name: caches directory owned by current user
  file:
    path: "/Library/Caches/Homebrew"
    state: directory
    owner: "{{ user }}"

- name: sborrazas repository added
  shell: "brew tap sborrazas/casks"
  args:
    creates: "/usr/local/Library/Taps/sborrazas"

- name: opt directory exists
  file:
    state: directory
    path: "/opt"
  sudo: True

- name: cask directory writable
  file:
    state: directory
    path: "/opt/homebrew-cask"
    owner: "{{ user }}"
  sudo: True

- name: homebrew up to date
  homebrew:
    update_homebrew: True

- name: homebrew packages installed
  homebrew:
    name: "{{ item }}"
    state: present
  with_items: homebrew_packages
