- name: emacs directory exists
  file:
    state: directory
    path: "{{ home_dir }}/.emacs.d"

- name: emacs modules copied
  copy:
    src: "modules/"
    dest: "{{ home_dir }}/.emacs.d/modules"

- name: irc logs directory exists
  file:
    state: directory
    path: "{{ home_dir }}/.logs"

- name: emacs init file exists
  template:
    src: "init.el.j2"
    dest: "{{ home_dir }}/.emacs.d/init.el"

- name: emacs config file exists
  copy:
    src: "config.el"
    dest: "{{ home_dir }}/.emacs.d/config.el"

- name: emacs bin exists
  copy:
    src: bin/emacs
    dest: "{{ home_dir }}/.bin/emacs"
  tags:
    - osx
