- name: bashrc copied
  template:
    src: bashrc.j2
    dest: "{{ home_dir }}/.bashrc"

- name: bash_profiled copied
  template:
    src: bash_profile.j2
    dest: "{{ home_dir }}/.bash_profile"

- name: default ssh key exists
  shell: ssh-keygen -f "{{ home_dir }}/.ssh/id_rsa" -N ""
  args:
    creates: "{{ home_dir }}/.ssh/id_rsa"

- name: helper binaries exist
  copy:
    src: bin/
    dest: "{{ home_dir }}/.bin"
    mode: 0755

- name: ansible global config file exists
  template:
    src: ansible.cfg.j2
    dest: "{{ home_dir }}/.ansible.cfg"

- name: Ubuntu updated
  apt:
    update_cache: True
    force_apt_get: True
  tags:
    - ubuntu
  become: True

- name: Ubuntu upgraded
  apt:
    upgrade: dist
    force_apt_get: True
  tags:
    - ubuntu
  become: True
