- name: terminal settings config file copied
  copy:
    src: "ocean-terminal.terminal"
    dest: "{{ home_dir }}/Desktop/ocean-terminal.terminal"

- name: keyboard defaults settings set
  script: set_keyboard_defaults.sh

- name: hacker defaults settings set
  script: set_hacker_defaults.sh

- name: copy finder sidebarlists
  copy:
    src: "com.apple.sidebarlists.plist"
    dest: "{{ home_dir }}/com.apple.sidebarlists.plist"

- name: set finder sidebarlists
  shell: "plutil -convert binary1 {{ home_dir }}/com.apple.sidebarlists.plist -o {{ home_dir }}/Library/Preferences/com.apple.sidebarlists.plist"
