- name: terminal settings config file copied
  copy:
    src: "ocean-terminal.terminal"
    dest: "{{ home_dir }}/Desktop/ocean-terminal.terminal"

- name: keyboard defaults settings set
  script: set_keyboard_defaults.sh

- name: hacker defaults settings set
  script: set_hacker_defaults.sh
